/* eslint-env browser, jest */

// NOTE: Still need to mock these modules, which was generated by scripts/generate-marko-module-map.js
const markoModulesMockingMap = {
  "marko/dist/components/helpers.js": "marko/dist/components/helpers-browser.js",
  "marko/dist/components/util.js": "marko/dist/components/util-browser.js"
};

// load Marko's browser-field dependecies on Node.js. This is done in order to load browser-side modules on server-side
function loadMarkoBrowserDependencies() {
  Object.keys(markoModulesMockingMap).forEach(moduleToMock => {
    jest.mock(moduleToMock, () => require.requireActual(markoModulesMockingMap[moduleToMock]));
  });
}

/* eslint global-require: 1 */
/* eslint import/no-dynamic-require: 1 */
exports.initComponent = function initComponent(componentFullPath) {
  loadMarkoBrowserDependencies();

  // require the component to test
  // eslint-disable-next-line import/no-dynamic-require, global-require
  const component = require(componentFullPath);

  // init marko component
  // eslint-disable-next-line global-require
  require('marko/components').init();

  return component;
};

exports.createTestSandbox = function createTestSandbox() {
  const el = document.createElement('div');
  el.id = 'test-sandbox';
  document.body.appendChild(el);

  return {
    el,

    /**
     * Render component into sandbox
     */
    renderComponent(component, input) {
      return component.render(input)
        .then((result) => {
          result.appendTo(this.el);
          return result.getComponent();
        });
    },

    getRenderedNodes() {
      return Array.from(this.el.childNodes);
    },

    /**
     * Remove test component from sandbox from DOM
     */
    reset() {
      document.body.removeChild(this.el);
    },
  };
};
